/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SalesItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SubscriptionPlan = IDL.Variant({
  'canceled' : IDL.Null,
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
  'freeTrial' : IDL.Null,
});
export const ImpactPortfolioData = IDL.Record({
  'environmentalImpactScore' : IDL.Nat,
  'impactDetails' : IDL.Text,
  'socialImpactScore' : IDL.Nat,
});
export const PortfolioType = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'impactPortfolioData' : IDL.Opt(ImpactPortfolioData),
});
export const PortfolioData = IDL.Record({
  'portfolioTypes' : IDL.Vec(PortfolioType),
});
export const Time = IDL.Int;
export const Advertisement = IDL.Record({
  'createdAt' : Time,
  'tone' : IDL.Text,
  'audience' : IDL.Text,
  'adCopy' : IDL.Text,
  'productOrService' : IDL.Text,
  'channel' : IDL.Text,
});
export const Campaign = IDL.Record({
  'endDate' : Time,
  'name' : IDL.Text,
  'advertisements' : IDL.Vec(Advertisement),
  'startDate' : Time,
});
export const MarketingData = IDL.Record({ 'campaigns' : IDL.Vec(Campaign) });
export const Subscription = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'plan' : SubscriptionPlan,
  'canceledAt' : IDL.Opt(Time),
  'startDate' : Time,
});
export const SalesData = IDL.Record({ 'items' : IDL.Vec(SalesItem) });
export const BusinessWorkspace = IDL.Record({
  'portfolioData' : IDL.Opt(PortfolioData),
  'marketingData' : IDL.Opt(MarketingData),
  'subscription' : IDL.Opt(Subscription),
  'owner' : IDL.Principal,
  'businessName' : IDL.Text,
  'salesData' : IDL.Opt(SalesData),
});
export const BusinessReport = IDL.Record({
  'gainsLosses' : IDL.Float64,
  'profitLoss' : IDL.Float64,
  'annualRevenue' : IDL.Float64,
});
export const SubscriptionStatus = IDL.Variant({
  'canceled' : IDL.Null,
  'paid' : IDL.Null,
  'activeTrial' : IDL.Null,
  'expiredTrial' : IDL.Null,
  'noSubscription' : IDL.Null,
});
export const SubscriptionWorkspaceDetails = IDL.Record({
  'status' : SubscriptionStatus,
  'endDate' : IDL.Opt(Time),
  'owner' : IDL.Principal,
  'plan' : SubscriptionPlan,
  'businessName' : IDL.Text,
  'canceledAt' : IDL.Opt(Time),
  'startDate' : Time,
});
export const SubscriptionAnalytics = IDL.Record({
  'emptySubscriptionsCount' : IDL.Nat,
  'monthlyCount' : IDL.Nat,
  'totalWorkspaces' : IDL.Nat,
  'monthlyPercent' : IDL.Float64,
  'workspacesExpiringFreeTrials' : IDL.Vec(SubscriptionWorkspaceDetails),
  'canceledCount' : IDL.Nat,
  'yearlyPercent' : IDL.Float64,
  'freeTrialCount' : IDL.Nat,
  'subscriptionDetails' : IDL.Vec(SubscriptionWorkspaceDetails),
  'expiredFreeTrialCount' : IDL.Nat,
  'expiringFreeTrialCount' : IDL.Nat,
  'yearlyCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSalesItem' : IDL.Func([SalesItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignSubscriptionPlan' : IDL.Func([SubscriptionPlan], [], []),
  'deleteSalesItem' : IDL.Func([IDL.Nat], [], []),
  'generateAiAdWorkspaces' : IDL.Func(
      [BusinessWorkspace, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [BusinessWorkspace],
      [],
    ),
  'getAllWorkspacesSortedByBusinessName' : IDL.Func(
      [],
      [IDL.Vec(BusinessWorkspace)],
      ['query'],
    ),
  'getBusinessReport' : IDL.Func([], [IDL.Opt(BusinessReport)], ['query']),
  'getBusinessWorkspace' : IDL.Func([], [BusinessWorkspace], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSalesData' : IDL.Func([], [IDL.Opt(SalesData)], ['query']),
  'getSubscriptionAnalytics' : IDL.Func([], [SubscriptionAnalytics], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'persistWorkspace' : IDL.Func([BusinessWorkspace], [], []),
  'updatePortfolioDataWorkspaces' : IDL.Func(
      [BusinessWorkspace, PortfolioData],
      [BusinessWorkspace],
      [],
    ),
  'updateSalesItem' : IDL.Func([SalesItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SalesItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SubscriptionPlan = IDL.Variant({
    'canceled' : IDL.Null,
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
    'freeTrial' : IDL.Null,
  });
  const ImpactPortfolioData = IDL.Record({
    'environmentalImpactScore' : IDL.Nat,
    'impactDetails' : IDL.Text,
    'socialImpactScore' : IDL.Nat,
  });
  const PortfolioType = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'impactPortfolioData' : IDL.Opt(ImpactPortfolioData),
  });
  const PortfolioData = IDL.Record({
    'portfolioTypes' : IDL.Vec(PortfolioType),
  });
  const Time = IDL.Int;
  const Advertisement = IDL.Record({
    'createdAt' : Time,
    'tone' : IDL.Text,
    'audience' : IDL.Text,
    'adCopy' : IDL.Text,
    'productOrService' : IDL.Text,
    'channel' : IDL.Text,
  });
  const Campaign = IDL.Record({
    'endDate' : Time,
    'name' : IDL.Text,
    'advertisements' : IDL.Vec(Advertisement),
    'startDate' : Time,
  });
  const MarketingData = IDL.Record({ 'campaigns' : IDL.Vec(Campaign) });
  const Subscription = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'plan' : SubscriptionPlan,
    'canceledAt' : IDL.Opt(Time),
    'startDate' : Time,
  });
  const SalesData = IDL.Record({ 'items' : IDL.Vec(SalesItem) });
  const BusinessWorkspace = IDL.Record({
    'portfolioData' : IDL.Opt(PortfolioData),
    'marketingData' : IDL.Opt(MarketingData),
    'subscription' : IDL.Opt(Subscription),
    'owner' : IDL.Principal,
    'businessName' : IDL.Text,
    'salesData' : IDL.Opt(SalesData),
  });
  const BusinessReport = IDL.Record({
    'gainsLosses' : IDL.Float64,
    'profitLoss' : IDL.Float64,
    'annualRevenue' : IDL.Float64,
  });
  const SubscriptionStatus = IDL.Variant({
    'canceled' : IDL.Null,
    'paid' : IDL.Null,
    'activeTrial' : IDL.Null,
    'expiredTrial' : IDL.Null,
    'noSubscription' : IDL.Null,
  });
  const SubscriptionWorkspaceDetails = IDL.Record({
    'status' : SubscriptionStatus,
    'endDate' : IDL.Opt(Time),
    'owner' : IDL.Principal,
    'plan' : SubscriptionPlan,
    'businessName' : IDL.Text,
    'canceledAt' : IDL.Opt(Time),
    'startDate' : Time,
  });
  const SubscriptionAnalytics = IDL.Record({
    'emptySubscriptionsCount' : IDL.Nat,
    'monthlyCount' : IDL.Nat,
    'totalWorkspaces' : IDL.Nat,
    'monthlyPercent' : IDL.Float64,
    'workspacesExpiringFreeTrials' : IDL.Vec(SubscriptionWorkspaceDetails),
    'canceledCount' : IDL.Nat,
    'yearlyPercent' : IDL.Float64,
    'freeTrialCount' : IDL.Nat,
    'subscriptionDetails' : IDL.Vec(SubscriptionWorkspaceDetails),
    'expiredFreeTrialCount' : IDL.Nat,
    'expiringFreeTrialCount' : IDL.Nat,
    'yearlyCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSalesItem' : IDL.Func([SalesItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignSubscriptionPlan' : IDL.Func([SubscriptionPlan], [], []),
    'deleteSalesItem' : IDL.Func([IDL.Nat], [], []),
    'generateAiAdWorkspaces' : IDL.Func(
        [BusinessWorkspace, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [BusinessWorkspace],
        [],
      ),
    'getAllWorkspacesSortedByBusinessName' : IDL.Func(
        [],
        [IDL.Vec(BusinessWorkspace)],
        ['query'],
      ),
    'getBusinessReport' : IDL.Func([], [IDL.Opt(BusinessReport)], ['query']),
    'getBusinessWorkspace' : IDL.Func([], [BusinessWorkspace], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSalesData' : IDL.Func([], [IDL.Opt(SalesData)], ['query']),
    'getSubscriptionAnalytics' : IDL.Func(
        [],
        [SubscriptionAnalytics],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'persistWorkspace' : IDL.Func([BusinessWorkspace], [], []),
    'updatePortfolioDataWorkspaces' : IDL.Func(
        [BusinessWorkspace, PortfolioData],
        [BusinessWorkspace],
        [],
      ),
    'updateSalesItem' : IDL.Func([SalesItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };