/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Advertisement {
  'createdAt' : Time,
  'tone' : string,
  'audience' : string,
  'adCopy' : string,
  'productOrService' : string,
  'channel' : string,
}
export interface BusinessWorkspace {
  'portfolioData' : [] | [PortfolioData],
  'marketingData' : [] | [MarketingData],
  'subscription' : [] | [Subscription],
  'owner' : Principal,
  'businessName' : string,
  'salesData' : [] | [SalesData],
}
export interface Campaign {
  'endDate' : Time,
  'name' : string,
  'advertisements' : Array<Advertisement>,
  'startDate' : Time,
}
export interface ImpactPortfolioData {
  'environmentalImpactScore' : bigint,
  'impactDetails' : string,
  'socialImpactScore' : bigint,
}
export interface MarketingData { 'campaigns' : Array<Campaign> }
export interface PortfolioData { 'portfolioTypes' : Array<PortfolioType> }
export interface PortfolioType {
  'name' : string,
  'description' : string,
  'impactPortfolioData' : [] | [ImpactPortfolioData],
}
export interface SalesData { 'items' : Array<SalesItem> }
export interface SalesItem {
  'status' : string,
  'name' : string,
  'amount' : number,
}
export interface Subscription {
  'endDate' : [] | [Time],
  'plan' : SubscriptionPlan,
  'canceledAt' : [] | [Time],
  'startDate' : Time,
}
export interface SubscriptionAnalytics {
  'emptySubscriptionsCount' : bigint,
  'monthlyCount' : bigint,
  'totalWorkspaces' : bigint,
  'monthlyPercent' : number,
  'workspacesExpiringFreeTrials' : Array<SubscriptionWorkspaceDetails>,
  'canceledCount' : bigint,
  'yearlyPercent' : number,
  'freeTrialCount' : bigint,
  'subscriptionDetails' : Array<SubscriptionWorkspaceDetails>,
  'expiredFreeTrialCount' : bigint,
  'expiringFreeTrialCount' : bigint,
  'yearlyCount' : bigint,
}
export type SubscriptionPlan = { 'canceled' : null } |
  { 'monthly' : null } |
  { 'yearly' : null } |
  { 'freeTrial' : null };
export type SubscriptionStatus = { 'canceled' : null } |
  { 'paid' : null } |
  { 'activeTrial' : null } |
  { 'expiredTrial' : null } |
  { 'noSubscription' : null };
export interface SubscriptionWorkspaceDetails {
  'status' : SubscriptionStatus,
  'endDate' : [] | [Time],
  'owner' : Principal,
  'plan' : SubscriptionPlan,
  'businessName' : string,
  'canceledAt' : [] | [Time],
  'startDate' : Time,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignSubscriptionPlan' : ActorMethod<[SubscriptionPlan], undefined>,
  'generateAiAdWorkspaces' : ActorMethod<
    [BusinessWorkspace, string, string, string, string, string],
    BusinessWorkspace
  >,
  'getAllWorkspacesSortedByBusinessName' : ActorMethod<
    [],
    Array<BusinessWorkspace>
  >,
  'getBusinessWorkspace' : ActorMethod<[], BusinessWorkspace>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSubscriptionAnalytics' : ActorMethod<[], SubscriptionAnalytics>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'persistWorkspace' : ActorMethod<[BusinessWorkspace], undefined>,
  'updatePortfolioDataWorkspaces' : ActorMethod<
    [BusinessWorkspace, PortfolioData],
    BusinessWorkspace
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];