/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PortfolioData {
    portfolioTypes: Array<PortfolioType>;
}
export type Time = bigint;
export interface ImpactPortfolioData {
    environmentalImpactScore: bigint;
    impactDetails: string;
    socialImpactScore: bigint;
}
export interface PortfolioType {
    name: string;
    description: string;
    impactPortfolioData?: ImpactPortfolioData;
}
export interface BusinessWorkspace {
    portfolioData?: PortfolioData;
    marketingData?: MarketingData;
    subscription?: Subscription;
    owner: Principal;
    businessName: string;
    salesData?: SalesData;
}
export interface SubscriptionAnalytics {
    emptySubscriptionsCount: bigint;
    monthlyCount: bigint;
    totalWorkspaces: bigint;
    monthlyPercent: number;
    workspacesExpiringFreeTrials: Array<SubscriptionWorkspaceDetails>;
    canceledCount: bigint;
    yearlyPercent: number;
    freeTrialCount: bigint;
    subscriptionDetails: Array<SubscriptionWorkspaceDetails>;
    expiredFreeTrialCount: bigint;
    expiringFreeTrialCount: bigint;
    yearlyCount: bigint;
}
export interface Advertisement {
    createdAt: Time;
    tone: string;
    audience: string;
    adCopy: string;
    productOrService: string;
    channel: string;
}
export interface SubscriptionWorkspaceDetails {
    status: SubscriptionStatus;
    endDate?: Time;
    owner: Principal;
    plan: SubscriptionPlan;
    businessName: string;
    canceledAt?: Time;
    startDate: Time;
}
export interface Subscription {
    endDate?: Time;
    plan: SubscriptionPlan;
    canceledAt?: Time;
    startDate: Time;
}
export interface SalesData {
    items: Array<SalesItem>;
}
export interface MarketingData {
    campaigns: Array<Campaign>;
}
export interface BusinessReport {
    gainsLosses: number;
    profitLoss: number;
    annualRevenue: number;
}
export interface Campaign {
    endDate: Time;
    name: string;
    advertisements: Array<Advertisement>;
    startDate: Time;
}
export interface SalesItem {
    id: bigint;
    status: string;
    name: string;
    amount: number;
}
export enum SubscriptionPlan {
    canceled = "canceled",
    monthly = "monthly",
    yearly = "yearly",
    freeTrial = "freeTrial"
}
export enum SubscriptionStatus {
    canceled = "canceled",
    paid = "paid",
    activeTrial = "activeTrial",
    expiredTrial = "expiredTrial",
    noSubscription = "noSubscription"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSalesItem(item: SalesItem): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignSubscriptionPlan(plan: SubscriptionPlan): Promise<void>;
    deleteSalesItem(itemId: bigint): Promise<void>;
    generateAiAdWorkspaces(anonymizedState: BusinessWorkspace, adCopy: string, productOrService: string, audience: string, tone: string, channel: string): Promise<BusinessWorkspace>;
    getAllWorkspacesSortedByBusinessName(): Promise<Array<BusinessWorkspace>>;
    getBusinessReport(): Promise<BusinessReport | null>;
    getBusinessWorkspace(): Promise<BusinessWorkspace>;
    getCallerUserRole(): Promise<UserRole>;
    getSalesData(): Promise<SalesData | null>;
    getSubscriptionAnalytics(): Promise<SubscriptionAnalytics>;
    isCallerAdmin(): Promise<boolean>;
    persistWorkspace(workspace: BusinessWorkspace): Promise<void>;
    updatePortfolioDataWorkspaces(anonymizedState: BusinessWorkspace, newPortfolioData: PortfolioData): Promise<BusinessWorkspace>;
    updateSalesItem(updatedItem: SalesItem): Promise<void>;
}
import type { BusinessReport as _BusinessReport, BusinessWorkspace as _BusinessWorkspace, ImpactPortfolioData as _ImpactPortfolioData, MarketingData as _MarketingData, PortfolioData as _PortfolioData, PortfolioType as _PortfolioType, SalesData as _SalesData, Subscription as _Subscription, SubscriptionAnalytics as _SubscriptionAnalytics, SubscriptionPlan as _SubscriptionPlan, SubscriptionStatus as _SubscriptionStatus, SubscriptionWorkspaceDetails as _SubscriptionWorkspaceDetails, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSalesItem(arg0: SalesItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalesItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalesItem(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignSubscriptionPlan(arg0: SubscriptionPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignSubscriptionPlan(to_candid_SubscriptionPlan_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignSubscriptionPlan(to_candid_SubscriptionPlan_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteSalesItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSalesItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSalesItem(arg0);
            return result;
        }
    }
    async generateAiAdWorkspaces(arg0: BusinessWorkspace, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<BusinessWorkspace> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAiAdWorkspaces(to_candid_BusinessWorkspace_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5);
                return from_candid_BusinessWorkspace_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAiAdWorkspaces(to_candid_BusinessWorkspace_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5);
            return from_candid_BusinessWorkspace_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWorkspacesSortedByBusinessName(): Promise<Array<BusinessWorkspace>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkspacesSortedByBusinessName();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkspacesSortedByBusinessName();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusinessReport(): Promise<BusinessReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessReport();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessReport();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusinessWorkspace(): Promise<BusinessWorkspace> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessWorkspace();
                return from_candid_BusinessWorkspace_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessWorkspace();
            return from_candid_BusinessWorkspace_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesData(): Promise<SalesData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesData();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesData();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionAnalytics(): Promise<SubscriptionAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionAnalytics();
                return from_candid_SubscriptionAnalytics_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionAnalytics();
            return from_candid_SubscriptionAnalytics_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async persistWorkspace(arg0: BusinessWorkspace): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.persistWorkspace(to_candid_BusinessWorkspace_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.persistWorkspace(to_candid_BusinessWorkspace_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePortfolioDataWorkspaces(arg0: BusinessWorkspace, arg1: PortfolioData): Promise<BusinessWorkspace> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePortfolioDataWorkspaces(to_candid_BusinessWorkspace_n5(this._uploadFile, this._downloadFile, arg0), to_candid_PortfolioData_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_BusinessWorkspace_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePortfolioDataWorkspaces(to_candid_BusinessWorkspace_n5(this._uploadFile, this._downloadFile, arg0), to_candid_PortfolioData_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_BusinessWorkspace_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSalesItem(arg0: SalesItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalesItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalesItem(arg0);
            return result;
        }
    }
}
function from_candid_BusinessWorkspace_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessWorkspace): BusinessWorkspace {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioData_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioData): PortfolioData {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioType): PortfolioType {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionAnalytics_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionAnalytics): SubscriptionAnalytics {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPlan_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionWorkspaceDetails_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionWorkspaceDetails): SubscriptionWorkspaceDetails {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PortfolioData]): PortfolioData | null {
    return value.length === 0 ? null : from_candid_PortfolioData_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ImpactPortfolioData]): ImpactPortfolioData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketingData]): MarketingData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subscription]): Subscription | null {
    return value.length === 0 ? null : from_candid_Subscription_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SalesData]): SalesData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessReport]): BusinessReport | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    portfolioData: [] | [_PortfolioData];
    marketingData: [] | [_MarketingData];
    subscription: [] | [_Subscription];
    owner: Principal;
    businessName: string;
    salesData: [] | [_SalesData];
}): {
    portfolioData?: PortfolioData;
    marketingData?: MarketingData;
    subscription?: Subscription;
    owner: Principal;
    businessName: string;
    salesData?: SalesData;
} {
    return {
        portfolioData: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.portfolioData)),
        marketingData: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.marketingData)),
        subscription: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.subscription)),
        owner: value.owner,
        businessName: value.businessName,
        salesData: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.salesData))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    portfolioTypes: Array<_PortfolioType>;
}): {
    portfolioTypes: Array<PortfolioType>;
} {
    return {
        portfolioTypes: from_candid_vec_n19(_uploadFile, _downloadFile, value.portfolioTypes)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    impactPortfolioData: [] | [_ImpactPortfolioData];
}): {
    name: string;
    description: string;
    impactPortfolioData?: ImpactPortfolioData;
} {
    return {
        name: value.name,
        description: value.description,
        impactPortfolioData: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.impactPortfolioData))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate: [] | [_Time];
    plan: _SubscriptionPlan;
    canceledAt: [] | [_Time];
    startDate: _Time;
}): {
    endDate?: Time;
    plan: SubscriptionPlan;
    canceledAt?: Time;
    startDate: Time;
} {
    return {
        endDate: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.endDate)),
        plan: from_candid_SubscriptionPlan_n28(_uploadFile, _downloadFile, value.plan),
        canceledAt: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.canceledAt)),
        startDate: value.startDate
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emptySubscriptionsCount: bigint;
    monthlyCount: bigint;
    totalWorkspaces: bigint;
    monthlyPercent: number;
    workspacesExpiringFreeTrials: Array<_SubscriptionWorkspaceDetails>;
    canceledCount: bigint;
    yearlyPercent: number;
    freeTrialCount: bigint;
    subscriptionDetails: Array<_SubscriptionWorkspaceDetails>;
    expiredFreeTrialCount: bigint;
    expiringFreeTrialCount: bigint;
    yearlyCount: bigint;
}): {
    emptySubscriptionsCount: bigint;
    monthlyCount: bigint;
    totalWorkspaces: bigint;
    monthlyPercent: number;
    workspacesExpiringFreeTrials: Array<SubscriptionWorkspaceDetails>;
    canceledCount: bigint;
    yearlyPercent: number;
    freeTrialCount: bigint;
    subscriptionDetails: Array<SubscriptionWorkspaceDetails>;
    expiredFreeTrialCount: bigint;
    expiringFreeTrialCount: bigint;
    yearlyCount: bigint;
} {
    return {
        emptySubscriptionsCount: value.emptySubscriptionsCount,
        monthlyCount: value.monthlyCount,
        totalWorkspaces: value.totalWorkspaces,
        monthlyPercent: value.monthlyPercent,
        workspacesExpiringFreeTrials: from_candid_vec_n37(_uploadFile, _downloadFile, value.workspacesExpiringFreeTrials),
        canceledCount: value.canceledCount,
        yearlyPercent: value.yearlyPercent,
        freeTrialCount: value.freeTrialCount,
        subscriptionDetails: from_candid_vec_n37(_uploadFile, _downloadFile, value.subscriptionDetails),
        expiredFreeTrialCount: value.expiredFreeTrialCount,
        expiringFreeTrialCount: value.expiringFreeTrialCount,
        yearlyCount: value.yearlyCount
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SubscriptionStatus;
    endDate: [] | [_Time];
    owner: Principal;
    plan: _SubscriptionPlan;
    businessName: string;
    canceledAt: [] | [_Time];
    startDate: _Time;
}): {
    status: SubscriptionStatus;
    endDate?: Time;
    owner: Principal;
    plan: SubscriptionPlan;
    businessName: string;
    canceledAt?: Time;
    startDate: Time;
} {
    return {
        status: from_candid_SubscriptionStatus_n40(_uploadFile, _downloadFile, value.status),
        endDate: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.endDate)),
        owner: value.owner,
        plan: from_candid_SubscriptionPlan_n28(_uploadFile, _downloadFile, value.plan),
        businessName: value.businessName,
        canceledAt: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.canceledAt)),
        startDate: value.startDate
    };
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    canceled: null;
} | {
    monthly: null;
} | {
    yearly: null;
} | {
    freeTrial: null;
}): SubscriptionPlan {
    return "canceled" in value ? SubscriptionPlan.canceled : "monthly" in value ? SubscriptionPlan.monthly : "yearly" in value ? SubscriptionPlan.yearly : "freeTrial" in value ? SubscriptionPlan.freeTrial : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    canceled: null;
} | {
    paid: null;
} | {
    activeTrial: null;
} | {
    expiredTrial: null;
} | {
    noSubscription: null;
}): SubscriptionStatus {
    return "canceled" in value ? SubscriptionStatus.canceled : "paid" in value ? SubscriptionStatus.paid : "activeTrial" in value ? SubscriptionStatus.activeTrial : "expiredTrial" in value ? SubscriptionStatus.expiredTrial : "noSubscription" in value ? SubscriptionStatus.noSubscription : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PortfolioType>): Array<PortfolioType> {
    return value.map((x)=>from_candid_PortfolioType_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BusinessWorkspace>): Array<BusinessWorkspace> {
    return value.map((x)=>from_candid_BusinessWorkspace_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubscriptionWorkspaceDetails>): Array<SubscriptionWorkspaceDetails> {
    return value.map((x)=>from_candid_SubscriptionWorkspaceDetails_n38(_uploadFile, _downloadFile, x));
}
function to_candid_BusinessWorkspace_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessWorkspace): _BusinessWorkspace {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PortfolioData_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortfolioData): _PortfolioData {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_PortfolioType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortfolioType): _PortfolioType {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionPlan_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): _SubscriptionPlan {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Subscription_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subscription): _Subscription {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    impactPortfolioData?: ImpactPortfolioData;
}): {
    name: string;
    description: string;
    impactPortfolioData: [] | [_ImpactPortfolioData];
} {
    return {
        name: value.name,
        description: value.description,
        impactPortfolioData: value.impactPortfolioData ? candid_some(value.impactPortfolioData) : candid_none()
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: Time;
    plan: SubscriptionPlan;
    canceledAt?: Time;
    startDate: Time;
}): {
    endDate: [] | [_Time];
    plan: _SubscriptionPlan;
    canceledAt: [] | [_Time];
    startDate: _Time;
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        plan: to_candid_SubscriptionPlan_n3(_uploadFile, _downloadFile, value.plan),
        canceledAt: value.canceledAt ? candid_some(value.canceledAt) : candid_none(),
        startDate: value.startDate
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    portfolioData?: PortfolioData;
    marketingData?: MarketingData;
    subscription?: Subscription;
    owner: Principal;
    businessName: string;
    salesData?: SalesData;
}): {
    portfolioData: [] | [_PortfolioData];
    marketingData: [] | [_MarketingData];
    subscription: [] | [_Subscription];
    owner: Principal;
    businessName: string;
    salesData: [] | [_SalesData];
} {
    return {
        portfolioData: value.portfolioData ? candid_some(to_candid_PortfolioData_n7(_uploadFile, _downloadFile, value.portfolioData)) : candid_none(),
        marketingData: value.marketingData ? candid_some(value.marketingData) : candid_none(),
        subscription: value.subscription ? candid_some(to_candid_Subscription_n12(_uploadFile, _downloadFile, value.subscription)) : candid_none(),
        owner: value.owner,
        businessName: value.businessName,
        salesData: value.salesData ? candid_some(value.salesData) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    portfolioTypes: Array<PortfolioType>;
}): {
    portfolioTypes: Array<_PortfolioType>;
} {
    return {
        portfolioTypes: to_candid_vec_n9(_uploadFile, _downloadFile, value.portfolioTypes)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): {
    canceled: null;
} | {
    monthly: null;
} | {
    yearly: null;
} | {
    freeTrial: null;
} {
    return value == SubscriptionPlan.canceled ? {
        canceled: null
    } : value == SubscriptionPlan.monthly ? {
        monthly: null
    } : value == SubscriptionPlan.yearly ? {
        yearly: null
    } : value == SubscriptionPlan.freeTrial ? {
        freeTrial: null
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PortfolioType>): Array<_PortfolioType> {
    return value.map((x)=>to_candid_PortfolioType_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
